import 'source-map-support/register.js'

export { type Config, getConfig } from '@/lib/config.js'
export { applyAudiosToVideo, extractAudio, getPictureFromVideo } from '@/lib/editor.js'
export { elevenlabs } from '@/lib/elevenlabs.dubbing.js'
export { removeVideosAndAudios } from '@/lib/fs.js'
export { googleDrive } from '@/lib/googledrive.js'
export { kinescope } from '@/lib/kinescope.js'
export { completionByOpenai } from '@/lib/openai.js'
export { extractSrtSimpleByRevai } from '@/lib/revai.js'
export { youtube } from '@/lib/youtube.js'
